-- 코드를 입력하세요
-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회

SELECT p.PRODUCT_ID, p.PRODUCT_NAME,
       (p.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE like '2022-05%'
    GROUP BY PRODUCT_ID
) o
ON o.PRODUCT_ID = p.PRODUCT_ID
ORDER BY TOTAL_SALES desc, p.PRODUCT_ID asc
;