-- 코드를 입력하세요
SELECT i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, (ROUND(AVG(REVIEW_SCORE), 2)) AS SCORE
FROM REST_INFO i
JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID
WHERE ADDRESS like '서울%'
GROUP BY r.REST_ID
ORDER BY SCORE desc, FAVORITES desc
;