SELECT p.PRODUCT_CODE AS PRODUCT_CODE, sum(o.SALES_AMOUNT * p.PRICE) AS SALES
FROM PRODUCT AS p
JOIN OFFLINE_SALE AS o
ON p.PRODUCT_ID = o.PRODUCT_ID
group by p.PRODUCT_CODE
ORDER BY SALES desc, PRODUCT_CODE asc;