-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람
-- 정답
SELECT u.USER_ID, u.NICKNAME, sum(b.price) AS TOTAL_SALES
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
WHERE status = 'DONE'
GROUP BY u.USER_ID
HAVING sum(b.PRICE) >= 700000
ORDER BY TOTAL_SALES asc
;